### ISSUE TITLE
Set up appveyor

### ISSUE THREAD

**Issue by jcrudy** [scikit-learn-contrib/py-earth#102]
Quoting @mblondel:

> You might want to add appveyor for testing py-earth on Windows. Here are the files used in scikit-learn and lightning:
> https://github.com/scikit-learn/scikit-learn/blob/master/appveyor.yml
> https://github.com/scikit-learn-contrib/lightning/blob/master/appveyor.yml

**Comment by mehdidc** [comment]
As the PR have been merged, I think we can close this issue.
