### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mblondel** [scikit-learn-contrib/py-earth#110]
Please upload the latest documentation to your `gh-pages` branch. The doc should then appear in http://contrib.scikit-learn.org/py-earth

There is already old doc in your `gh-pages` branch but it doesn't appear on the website. I think you need to push something to trigger a copy of the doc.

You can have a look at project-template for an example:
https://github.com/scikit-learn-contrib/project-template/tree/gh-pages

See also:
https://help.github.com/articles/creating-project-pages-manually/

**Comment by mehdidc** [comment]
Thanks, I updated the branch gh-pages and indeed the doc appears now.

**Comment by mblondel** [comment]
Thanks a lot, closing.
