### ISSUE TITLE
Include README.md in package

### ISSUE THREAD

**Issue by nicodv** [scikit-learn-contrib/py-earth#118]
When I built the package myself using `python setup.py sdist` and deployed the py-earth-0.1.0.tar.gz afterwards, I got the following error while installing:

>     Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-RfoSWF/py-earth/setup.py", line 142, in <module>
        setup_package()
      File "/tmp/pip-build-RfoSWF/py-earth/setup.py", line 112, in setup_package
        'long_description': codecs.open('README.md', mode='r', encoding='utf-8').read(),
      File "/opt/mydir/virtualenvs/venv/lib/python2.7/codecs.py", line 881, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'README.md'

`setup.py` attempts to read README.md but it was not included in the package.

This can be easily solved by including README.md in MANIFEST.in. I can imagine you'd want to maybe include LICENSE.txt and CHANGES.txt too.

**Comment by jcrudy** [comment]
@nicodv Thanks for the report.  Should be fixed now in master.
