### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by florakarniav** [scikit-learn-contrib/py-earth#126]
Hi, 
I get the following error when trying to run the most basic example(in the readme file).
Any idea why?
Thank you in advance

Traceback (most recent call last):
  File "example.py", line 2, in <module>
    from pyearth import Earth
  File "/home/flo/mars/py-earth/pyearth/__init__.py", line 8, in <module>
    from .earth import Earth
  File "/home/flo/mars/py-earth/pyearth/earth.py", line 1, in <module>
    from ._forward import ForwardPasser
ImportError: No module named _forward

**Comment by mehdidc** [comment]
Hello,

it looks like the 'so' (_forward.so etc) files are not found. Could you please show  the content of directory where py-earth hsas been installed ? you could know it by doing an 'import pyearth;print(pyearth.__file__)' and list the directory where the shown file is located.

**Comment by florakarniav** [comment]
Hi and thank you for your response,

it seems that even just 'import pyearth' does not work.
This line: _ImportError: No module named _forward_ made me look for issues in the _forward module which is actually a Cython module so the problem was that I need to run my .py with Cython.

**Comment by PeterJacob** [comment]
I actually got this error as well when I first installed py-earth. Curiously it is no longer a problem after running pip uninstall py-earth, and running python setup.py install again.

**Comment by jcrudy** [comment]
@PeterJacob For the record, what operating system and python version are you using?

**Comment by jcharit1** [comment]
I encountered this error too. Try changing out of the py-earth installation directory (i.e. cd ~), then try executing python and importing the package.
