### ISSUE TITLE
ImportError: no module named 'pyearth'

### ISSUE THREAD

**Issue by JustinCastillo** [scikit-learn-contrib/py-earth#136]
Hi! I am new to python and linux in general and I can't seem to import pyearth.

I have tried following the instructions on the readme as follows:

> git clone git://github.com/scikit-learn-contrib/py-earth.git
> cd py-earth
> sudo python setup.py install
> but I still can't seem to import pyearh.

Thank you for your time and I'm sorry to ask this basic question

**Comment by jcrudy** [comment]
@JustinCastillo Can you show the output from those commands?  Particularly from the last one.

**Comment by JustinCastillo** [comment]
@jcrudy Thank you for responding sir! Here is the output following the command sudo python setup.py install:

> running install
> running bdist_egg
> running egg_info
> writing requirements to py_earth.egg-info/requires.txt
> writing py_earth.egg-info/PKG-INFO
> writing top-level names to py_earth.egg-info/top_level.txt
> writing dependency_links to py_earth.egg-info/dependency_links.txt
> reading manifest file 'py_earth.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no files found matching 'pyearth/test/pathological_data'
> writing manifest file 'py_earth.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_basis.pxd -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_types.c -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/__init__.py -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_knot_search.c -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_util.pxd -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_knot_search.so -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_forward.so -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_forward.c -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_types.so -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_record.pxd -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_pruning.so -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_qr.pxd -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_record.c -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_pruning.c -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_qr.so -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_basis.so -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/earth.py -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_version.py -> build/bdist.linux-x86_64/egg/pyearth
> creating build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/__init__.py -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/test_qr.py -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/testing_utils.py -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/test_data.csv -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/test_pruning.py -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/test_forward.py -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/forward_regress.txt -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/test_export.py -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/earth_regress_missing_data.txt -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/earth_regress_smooth.txt -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/test_knot_search.py -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/earth_linvars_regress.txt -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/test_util.py -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/earth_regress.txt -> build/bdist.linux-x86_64/egg/pyearth/test
> copying build/lib.linux-x86_64-2.7/pyearth/test/test_earth.py -> build/bdist.linux-x86_64/egg/pyearth/test
> creating build/bdist.linux-x86_64/egg/pyearth/test/record
> copying build/lib.linux-x86_64-2.7/pyearth/test/record/__init__.py -> build/bdist.linux-x86_64/egg/pyearth/test/record
> copying build/lib.linux-x86_64-2.7/pyearth/test/record/test_forward_pass.py -> build/bdist.linux-x86_64/egg/pyearth/test/record
> copying build/lib.linux-x86_64-2.7/pyearth/test/record/test_pruning_pass.py -> build/bdist.linux-x86_64/egg/pyearth/test/record
> creating build/bdist.linux-x86_64/egg/pyearth/test/basis
> copying build/lib.linux-x86_64-2.7/pyearth/test/basis/base.py -> build/bdist.linux-x86_64/egg/pyearth/test/basis
> copying build/lib.linux-x86_64-2.7/pyearth/test/basis/__init__.py -> build/bdist.linux-x86_64/egg/pyearth/test/basis
> copying build/lib.linux-x86_64-2.7/pyearth/test/basis/test_smoothed_hinge.py -> build/bdist.linux-x86_64/egg/pyearth/test/basis
> copying build/lib.linux-x86_64-2.7/pyearth/test/basis/test_basis.py -> build/bdist.linux-x86_64/egg/pyearth/test/basis
> copying build/lib.linux-x86_64-2.7/pyearth/test/basis/test_missingness.py -> build/bdist.linux-x86_64/egg/pyearth/test/basis
> copying build/lib.linux-x86_64-2.7/pyearth/test/basis/test_hinge.py -> build/bdist.linux-x86_64/egg/pyearth/test/basis
> copying build/lib.linux-x86_64-2.7/pyearth/test/basis/test_linear.py -> build/bdist.linux-x86_64/egg/pyearth/test/basis
> copying build/lib.linux-x86_64-2.7/pyearth/test/basis/test_constant.py -> build/bdist.linux-x86_64/egg/pyearth/test/basis
> copying build/lib.linux-x86_64-2.7/pyearth/_forward.pxd -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_pruning.pxd -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_util.so -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_types.pxd -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/export.py -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_record.so -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_basis.c -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_knot_search.pxd -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_util.c -> build/bdist.linux-x86_64/egg/pyearth
> copying build/lib.linux-x86_64-2.7/pyearth/_qr.c -> build/bdist.linux-x86_64/egg/pyearth
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/__init__.py to __init__.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/earth.py to earth.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/_version.py to _version.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/__init__.py to __init__.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/test_qr.py to test_qr.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/testing_utils.py to testing_utils.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/test_pruning.py to test_pruning.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/test_forward.py to test_forward.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/test_export.py to test_export.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/test_knot_search.py to test_knot_search.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/test_util.py to test_util.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/test_earth.py to test_earth.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/record/__init__.py to __init__.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/record/test_forward_pass.py to test_forward_pass.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/record/test_pruning_pass.py to test_pruning_pass.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/basis/base.py to base.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/basis/__init__.py to __init__.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/basis/test_smoothed_hinge.py to test_smoothed_hinge.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/basis/test_basis.py to test_basis.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/basis/test_missingness.py to test_missingness.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/basis/test_hinge.py to test_hinge.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/basis/test_linear.py to test_linear.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/test/basis/test_constant.py to test_constant.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/export.py to export.pyc
> creating stub loader for pyearth/_util.so
> creating stub loader for pyearth/_basis.so
> creating stub loader for pyearth/_record.so
> creating stub loader for pyearth/_pruning.so
> creating stub loader for pyearth/_forward.so
> creating stub loader for pyearth/_knot_search.so
> creating stub loader for pyearth/_qr.so
> creating stub loader for pyearth/_types.so
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/_util.py to _util.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/_basis.py to _basis.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/_record.py to _record.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/_pruning.py to _pruning.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/_forward.py to _forward.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/_knot_search.py to _knot_search.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/_qr.py to _qr.pyc
> byte-compiling build/bdist.linux-x86_64/egg/pyearth/_types.py to _types.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying py_earth.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying py_earth.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying py_earth.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying py_earth.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying py_earth.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
> zip_safe flag not set; analyzing archive contents...
> pyearth.test.test_forward: module references __file__
> pyearth.test.test_util: module references __file__
> pyearth.test.test_pruning: module references __file__
> pyearth.test.test_earth: module references __file__
> pyearth.test.basis.base: module references __file__
> creating 'dist/py_earth-0.1.0-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing py_earth-0.1.0-py2.7-linux-x86_64.egg
> removing '/usr/local/lib/python2.7/dist-packages/py_earth-0.1.0-py2.7-linux-x86_64.egg' (and everything under it)
> creating /usr/local/lib/python2.7/dist-packages/py_earth-0.1.0-py2.7-linux-x86_64.egg
> Extracting py_earth-0.1.0-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
> py-earth 0.1.0 is already the active version in easy-install.pth
> 
> Installed /usr/local/lib/python2.7/dist-packages/py_earth-0.1.0-py2.7-linux-x86_64.egg
> Processing dependencies for py-earth==0.1.0
> Searching for sphinx-gallery==0.1.4
> Best match: sphinx-gallery 0.1.4
> Processing sphinx_gallery-0.1.4-py2.7.egg
> sphinx-gallery 0.1.4 is already the active version in easy-install.pth
> Installing copy_sphinxgallery.sh script to /usr/local/bin
> 
> Using /usr/local/lib/python2.7/dist-packages/sphinx_gallery-0.1.4-py2.7.egg
> Searching for scikit-learn==0.17.1
> Best match: scikit-learn 0.17.1
> Processing scikit_learn-0.17.1-py2.7-linux-x86_64.egg
> scikit-learn 0.17.1 is already the active version in easy-install.pth
> 
> Using /usr/local/lib/python2.7/dist-packages/scikit_learn-0.17.1-py2.7-linux-x86_64.egg
> Finished processing dependencies for py-earth==0.1.0

**Comment by jcrudy** [comment]
@JustinCastillo I don't see any problems there.  Is it possible you have more than one instance of Python installed and you're installing in one and attempting to import in the other?  Have you been able to install other packages using the same method?  If you're using virtualenv or conda environments that might also be a factor.

**Comment by jcrudy** [comment]
Closing this.  @JustinCastillo, feel free to reopen if you're still having the problem.
