### ISSUE TITLE
Question about MultiColumn Data

### ISSUE THREAD

**Issue by adumudaliar** [scikit-learn-contrib/py-earth#139]
Hello,
          I am a new python/pyearth user. I am also new to MARS.  
I have a dataset with multiple input parameters/columns/predictors.
I read the multi column example and had a few questions.

From the (multi column) example, it seems like, you have two input columns/ and a single output. However, I see that you have created two columns of output ( of the same/single column) calling it Y1/Y2.

Question is: If I have n input columns/1 output column... do i make n columns of the output column, to pass to Earth implementation ?

I want to understand the impact of each of the input paramters on the output, so will n input columns/n output columns(copy of the single output column) work ?

Please let me know.

Thanks,
Vinod

**Comment by jcrudy** [comment]
@adumudaliar The multicolumn example applies to the situation of having multiple response columns.  I will make a note to make that clearer in the code.  As you have a single response column and multiple predictor columns, you would be better off looking at a simpler example such as [plot_v_function](https://github.com/scikit-learn-contrib/py-earth/blob/master/examples/plot_v_function.py).  

> I want to understand the impact of each of the input paramters on the output, so will n input columns/n output columns(copy of the single output column) work ?

You definitely don't want to copy your output column multiple times.  Py-earth will automatically try to use all input columns to predict your output column.  Can you explain more what you mean by "understand the impact"?  Py-earth will give you a predictive model, but understanding the causal mechanisms behind the processes generating your data is beyond its capabilities, as well as those of any other machine learning method, barring additional assumptions.
