### ISSUE TITLE
Segmentation fault in  pyearth.tests.test_earth.test_check_estimator

### ISSUE THREAD

**Issue by mehdidc** [scikit-learn-contrib/py-earth#145]
Seen in #144, it also seems to happen with the current master (commit : fd1dca92dadd01483db0023a79a8e75cbc76a708)

it is not deterministic, it does not happen all the time.
it happens in python 2.7 and python 3.4 .

I can get it by launching:

python -c 'from pyearth.test.test_earth import test_check_estimator;test_check_estimator()'

@jcrudy could you please tell whether you can reproduce this ?

**Comment by jcrudy** [comment]
@mehdidc Yes, I am able to reproduce this.  I'm not sure what's happening, but it's happening now because of the new version of scikit-learn.

**Comment by jcrudy** [comment]
I did a little testing and it looks like the segfault happens in the `check_fit2d_1sample` function in `sklearn.utils.estimator_checks` (commenting out that check eliminates the segfault).  `check_fit2d_1sample` attempts to fit an `Earth` model with only one row of data.  I'm guessing that's what causes the segfault.  However, I haven't managed to get the segfault to happen by trying the same thing in a script.

**Comment by jcrudy** [comment]
I think I fixed the problem.  Will create a pull request.

**Comment by jcrudy** [comment]
Fixed.
