### ISSUE TITLE
documentation of bivariate responses?

### ISSUE THREAD

**Issue by empirical-bayesian** [scikit-learn-contrib/py-earth#158]
This isn't really an issue. It's more like a question, and it really is much more suitable for an open discussion or help forum for py-earth than for here.  If there is such a thing, could someone point me to it, and then this Issue can be closed. 

Otherwise, I was looking for an example of how one can set up a case for a bivariate response model for py-earth.  Is it as simple as submitting an n-by-2 _numpy_ matrix for the second argument to the **_fit_** method?  From the API, I assume so.  But where do I find what's returned in the case of multivariate _y_, that is, with p > 1?

**Comment by empirical-bayesian** [comment]
Figured it out from code and such.

**Comment by jcrudy** [comment]
@empirical-bayesian Excellent.  If anyone else comes across this thread before I get around to writing better documentation, a good place to look in in examples/plot_sine_wave_2d.py.
