### ISSUE TITLE
combine py-earth with  sklearn.ensemble.BaggingRegressor

### ISSUE THREAD

**Issue by zrq0123** [scikit-learn-contrib/py-earth#163]
Hi, in my project, I combine pyearth with BaggingRegressor to get a bagging result, my code is as follow:
`bagger=BaggingRegressor(base_estimator=Earth(penalty =20,feature_importance_type="rss",max_terms =10,use_fast=True,allow_missing=True),n_estimators=1000,n_jobs=-1,random_state=random.randint(1,100),bootstrap=True,max_features =5)`
In one small scale dataset, the code run correctly, but in a large one (4381 cols * 832 rows), the code give a `ValueError: assignment destination is read-only`, and if I set the parameter n_jobs =1 ,the code can run correctly. So the py-earth have some bugs or error  combine with BaggingRegressor on multiple CPUs, which can speed up the computing

**Comment by jcrudy** [comment]
@zrq0123 Thank you for reporting this.  Can you give me the full stack trace for this error?  Also, if possible, can you give me detailed code, data, or steps to reproduce the error?  I know it can be difficult to do this with data-dependent errors, but anything you can provide might help.  Does it happen on every sufficiently large input?  Finally, can you give me information on your platform: operating system, python version, version of scikit-learn, scipy, numpy?

**Comment by zrq0123** [comment]
Thanks for you quick replying, I have sent the code and dataset to your Gmail.

**Comment by jcrudy** [comment]
This should now be fixed in master.  Closing issue.  @zrq0123, please comment and reopen if this problem persists for you.
