### ISSUE TITLE
Does it support python3?

### ISSUE THREAD

**Issue by wu-yuanyi** [scikit-learn-contrib/py-earth#164]
It stuck at

```
Searching for scikit-learn>=0.16
Reading https://pypi.python.org/simple/scikit-learn/
Downloading https://pypi.python.org/packages/c2/38/e3b0333e661ab411545583cb24940223917fe7ffc9c68a77730dce3b10b0/scikit-learn-0.19.0.tar.gz#md5=5e7b6cb30f77ad0f219be08242313d88
```

**Comment by jcrudy** [comment]
Python 3 is supported and tested, although I use 2.7 so if there are Python 3 bugs I'm less likely to find them.  Can you give some context for the output you posted above?  It looks like you're installing scikit-learn, not py-earth.

**Comment by wu-yuanyi** [comment]
I am in China where the GFW obstructs users surf the Internet. There is no prompt when I use `sudo python3 setup.py install`. So, I mistakenly thought there is an error.
After I spent 10 mins to do `pip3 install scikit-learn`.  `sudo python3 setup.py install` runs quickly.

**Comment by jcrudy** [comment]
Ah, that makes sense.  The hanging was due to some blocked connection.  Closing this issue.  Thanks for reporting.
