### ISSUE TITLE
no model named pyearth

### ISSUE THREAD

**Issue by hassan-bdw** [scikit-learn-contrib/py-earth#174]
Hi all

I'm trying to use the pyearth package on the jupyter notebook to develop some models using the MARS algorithm and compare with couple of scikit-learn support vector machine model.

When I import the the package I get an error that the package doesn't exist. however there is a directory created in the anaconda directory, I used anaconda to install scikit-learn and to use the jupyter notebook.

Do I have to install the package in any other way or I'm missing some crucial point?
**NB:** I already updated Scipy, Numpy and scikit-learn

**Comment by jcrudy** [comment]
@hassan-bdw Can you post exactly what commands you used to install py-earth, the full stack trace for whatever error you're getting, and any other data you think might be pertinent?

Note: py-earth is on pypi under sklearn-contrib-py-earth, so you can try installing it using pip and see if that helps.

**Comment by hassan-bdw** [comment]
@jcrudy Hey thank you for your fast reply, actually I would like to thank you also for your suggestion on using pip, i found a page that includes the necessary command to install py-earth using pip and now I can import the package in jupyter notebook.

As an answer for your first question, I used the git clone command found on the github page of the pyearth package, as for the trace of the installation, I was getting some sort of warning messages regarding the matching of the Numpy version..I didn't save the messages and I don't want to try and replicate them since I don't want to risk and try it right.

thanks again.
