### ISSUE TITLE
 X and y do not have compatible dimensions while they do

### ISSUE THREAD

**Issue by florakarniav** [scikit-learn-contrib/py-earth#176]
Hello,
I get the ValueError: X and y do not have compatible dimensions with files that contain the exact same number of rows. 

```
print X.shape[0]
print y.shape[0]
```
return the same number. Any ideas?

Thank you

**Comment by jcrudy** [comment]
@florakarniav I'm not sure what could be going wrong.  I may be able to help if you share more of your code.

**Comment by florakarniav** [comment]
Hello, 
It turns out there was something wrong with the encoding of the input dataset files,
thank you for your quick response.
