### ISSUE TITLE
Conda forge package name

### ISSUE THREAD

**Issue by rth** [scikit-learn-contrib/py-earth#178]
I continued @mehdidc's work on adding py-earth to conda-forge in https://github.com/conda-forge/staged-recipes/pull/5108 and was wondering what should be the package name there (`py-earth`, `pyearth`, `sklearn-contrib-py-earth`)?  Thanks.

Also related discussion in https://github.com/scikit-learn-contrib/scikit-learn-contrib/issues/27

**Comment by jcrudy** [comment]
@rth Thank you!   I think the name should be sklearn-contrib-py-earth, to match the name currently on pypi.

**Comment by rth** [comment]
Great thank you for the response.
