### ISSUE TITLE
py-earth build error. 

### ISSUE THREAD

**Issue by santoshgawande** [scikit-learn-contrib/py-earth#208]
I am trying to install using pip3 install sklearn-contrib-py-earth package. So it is not installed properly. It caused error to build. I am using python3.6.9 version and it install my local system
![Screenshot from 2020-12-12 14-08-01](https://user-images.githubusercontent.com/37923311/101979496-86824a00-3c83-11eb-9155-82462cf973f6.png)

![Screenshot from 2020-12-12 14-05-15](https://user-images.githubusercontent.com/37923311/101979461-44f19f00-3c83-11eb-9d70-504bd4d74e02.png)

**Comment by kevin-dietz** [comment]
@santoshgawande try cloning the py-earth repo and compiling from that:
```
git clone git://github.com/jcrudy/py-earth.git
cd py-earth
python setup.py build_ext --inplace --cythonize
```

Alternatively you can try building from branch 191:
```
git clone -b issue191 git://github.com/jcrudy/py-earth.git
cd py-earth
python setup.py install --cythonize
```

**Comment by maruti-iitm** [comment]
For me the alternate build from branch 191 solved the problem. Thanks a lot!

**Comment by ash07uph** [comment]
The build from branch 191 is giving me the following error of Microsoft Visual C++ 14.0
![image](https://user-images.githubusercontent.com/4965831/109465171-c9d3a400-7a8d-11eb-943b-5e06deca51d8.png)

**Comment by kevin-dietz** [comment]
@ash07uph Sounds like you need to upgrade C++ to 14.0...

**Comment by santoshgawande** [comment]
@kevin-dietz  Thank you for this.Using this solved my issue.

> git clone git://github.com/jcrudy/py-earth.git
cd py-earth
python setup.py build_ext --inplace --cythonize
