### ISSUE TITLE
Is pyearth a a trademarked algorithm?

### ISSUE THREAD

**Issue by apatange-source** [scikit-learn-contrib/py-earth#220]
This isn't technically an issue. I just wanted to know whether I can use pyearth in a commercial project. I know the name MARS is trademarked so I just wanted to be sure.

**Comment by kevin-dietz** [comment]
@apatange-source Yes you can use it in a commercial application. You can view the license here: https://github.com/scikit-learn-contrib/py-earth/blob/master/LICENSE.txt
