### ISSUE TITLE
py-earth fails for multi-column regression

### ISSUE THREAD

**Issue by abhishekkrthakur** [scikit-learn-contrib/py-earth#49]
py-Earth fails when fitting a multi column [m x n] label matrix with the two-dimensional training data. This can be considered as an enhancement

model.fit(X_train, y_train)
  File "/Library/Python/2.7/site-packages/pyearth/earth.py", line 331, in fit
    X, y, sample_weight = self._scrub(X, y, sample_weight)
  File "/Library/Python/2.7/site-packages/pyearth/earth.py", line 262, in _scrub
    y = y.reshape(y.shape[0])
ValueError: total size of new array must be unchanged

**Comment by aleon1138** [comment]
How would this work? Would it be a separate model for each column of Y or would it be a single model that would jointly best explain all columns of Y?

**Comment by mehdidc** [comment]
@aleon1138  In the earth R package (Check section 2.9, http://www.milbo.org/doc/earth-notes.pdf) , it is one model for each column of Y except that that they share the same set of basis functions and the models are optimized to minimize the overall GCV (the sum of GCVs of all the models). However they don't share the basis functions coeficients, each model has its own set of coeficients for basis functions

**Comment by jcrudy** [comment]
@aleon1138  Yes, the way @mehdidc described is also how I understand it and would want to implement it.

**Comment by jcrudy** [comment]
This was implemented by @mehdidc .
