### ISSUE TITLE
pip fails to install at same time of numpy

### ISSUE THREAD

**Issue by Marco-Santoni** [scikit-learn-contrib/py-earth#60]
If neither `numpy` nor `pyearth` are installed, and we install both of them by:

```
$ pip install -r requirements.txt
```

where `requirements.txt`:

```
numpy
scipy
-e git+https://github.com/jcrudy/py-earth.git#egg=py-earth
```

Throws `ImportError: no module named numpy` when installing `pyearth`. Refer to [this issue](https://github.com/pypa/pip/issues/272) and [this issue](https://github.com/pypa/pip/issues/25) to see how pip works in this case.

**Comment by jcrudy** [comment]
Fixed by @mehdidc in PR #98.
