### ISSUE TITLE
Compatibility of Earth with scikit-learn API

### ISSUE THREAD

**Issue by mehdidc** [scikit-learn-contrib/py-earth#74]
In Earth :
- __pull_unknown_args and __unprune  are never called
- we don't need get_penalty, we can just use penalty, the default value is already 3.
- __repr__ and __str__ are already in BaseEstimator

can we remove them ?

Also, trace forward_trace pruning_trace summary are public methods and are then not compatible with scikit learn API, what about transforming them into functions, as done in #72 ?

**Comment by jcrudy** [comment]
Sounds good to me. I'm currently traveling without my computer, but will be back around the 15th.

**Comment by jcrudy** [comment]
Closing this issue.  Now that py-earth is not going into scikit-learn, further compatibility is not necessary except as far as is needed for scikit-learn-contrib.
