### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by mehdidc** [scikit-learn-contrib/py-earth#76]
Can we have a first release and put py-earth on pypi ?

**Comment by jcrudy** [comment]
Yeah, I think it's a good idea. I'm currently traveling without computer, but can look into it when I get back around the 15th or so.

**Comment by mangecoeur** [comment]
+1

**Comment by sylvainr** [comment]
Would be also great to create a binstar package (https://binstar.org/) such that people without a compilation environment can use this awesome tool.

I guess on the long run, getting it integrated to sklearn would make it much more diffused.

**Comment by springcoil** [comment]
Are there plans to integrate this into sklearn?

**Comment by jcrudy** [comment]
Not currently.  See issue #94.  Perhaps I should update the readme to reflect this.

**Comment by jcrudy** [comment]
@mehdidc I think there are three things that need to happen before release:

1.  Merge the `rewrite_forward_pass` branch into master.  There is one problem in that branch that still needs working out.  I will create an issue for it and tag you.  
2.  Fix issue #60 or decide not to fix it.
3.  Go through existing issues and close or mark for future releases (to make sure we're not leaving out something important).

Most of this is on me, but I could use as much help as you're available to give.  If you want to take something, let me know so we don't duplicate work.  Once these things are done I'll tag a release and publish to pypi (and look into the binstar/binary release issue).

**Comment by mehdidc** [comment]
@jcrudy Ok, I am right now working on 2 it is almost fixed, I will further work on 1.

**Comment by jcrudy** [comment]
More than a year later, I've finally published py-earth to pypi.  It can be found under the name sklearn-contrib-py-earth.
