### ISSUE TITLE
Meet scikit-learn-contrib requirements 

### ISSUE THREAD

**Issue by jcrudy** [scikit-learn-contrib/py-earth#96]
I think @mehdidc has already done everything necessary to meet the requirements of contrib.  However, @mblondel, could you sign off on this?  With confirmation from you, the next priority will be a tagged release and publication on pypi (see issue #76 ).  

@mehdidc I'm assigning this issue to you because I think you've basically already solved it.  If there's more that needs to be done and you want to assign it back to me, please feel free.  Not trying to push more work onto you than you want to take:).

**Comment by mblondel** [comment]
In lightning, we are using sklearn-contrib-lightning as the package name on pypi
https://github.com/scikit-learn-contrib/lightning

It would be nice if you could use the same convention.

**Comment by mblondel** [comment]
> @mblondel, could you sign off on this?

Sure, I will have a look over the week-end.

**Comment by jcrudy** [comment]
@mblondel Much appreciated.  So to follow the convention, our pypi name would be sklearn-contrib-py-earth.

**Comment by mblondel** [comment]
I got a test failure.

```
======================================================================
ERROR: pyearth.test.test_earth.test_untrained
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mblondel/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/mblondel/Desktop/projects/py-earth/pyearth/test/test_earth.py", line 436, in test_untrained
    assert_raises(NotFittedError, model.predict, X)
  File "/Users/mblondel/anaconda/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/Users/mblondel/Desktop/projects/py-earth/pyearth/earth.py", line 851, in predict
    B = self.transform(X, missing)
  File "/Users/mblondel/Desktop/projects/py-earth/pyearth/earth.py", line 1004, in transform
    check_is_fitted(self, "basis_")
  File "/Users/mblondel/Desktop/projects/scikit-learn/sklearn/utils/validation.py", line 685, in check_is_fitted
    raise _NotFittedError(msg % {'name': type(estimator).__name__})
NotFittedError: This Earth instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

----------------------------------------------------------------------
```
FYI, I am using scikit-learn master.

**Comment by mblondel** [comment]
This is very hackish:
https://github.com/scikit-learn-contrib/py-earth/blob/master/pyearth/test/test_earth.py#L45

We need to support this at the API level. CC @amueller

**Comment by mblondel** [comment]
You might want to add appveyor for testing py-earth on Windows. Here are the files used in scikit-learn and lightning:
https://github.com/scikit-learn/scikit-learn/blob/master/appveyor.yml
https://github.com/scikit-learn-contrib/lightning/blob/master/appveyor.yml

**Comment by amueller** [comment]
I know. The current "estimator_type" is a bad idea and should be a dict "estimator_tags".

**Comment by jcrudy** [comment]
Thanks, @mblondel.  I'll get to work on these notes and see if I can reproduce the test failure.

**Comment by jcrudy** [comment]
Version 0.1.0 is now on pypi.
